management:
  endpoints:
    web:
      exposure:
        include: '*'
#server:
 # port: 8081
  
spring:
  application:
    name: GREET-API
  boot:
    admin:
      client:
        url: http://localhost:8085

msg: Hello Darling