server:
  port: 9091
  
spring:
  application:
    name: WELC-API
    
  boot:
    admin:
      client:
        url: http://localhost:8085/
        
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
#eureka:
 # client:
  #  prefer-ip-address: true  
    
 # instance:
  #  prefer-ip-address: true
      